import turtle
turtle.speed(0)
turtle.shape('turtle')
turtle.color("yellow")
turtle.begin_fill()
turtle.circle(150)
turtle.end_fill()
turtle.penup()
turtle.goto(-65 , 195)
turtle.color("blue")
turtle.pendown()
turtle.begin_fill()
turtle.circle(15)
turtle.end_fill()
turtle.penup()
turtle.goto(65 , 195)
turtle.pendown()
turtle.begin_fill()
turtle.circle(15)
turtle.end_fill()
turtle.penup()
turtle.goto(0 , 170)
turtle.pendown()
turtle.color("black")
turtle.width(10)
turtle.goto(0 , 135)
turtle.penup()
turtle.color("red")
turtle.goto(60,100)
turtle.right(90)
turtle.pendown()
i = 180
while i > 0:
  i -= 1
  turtle.forward(1)
  turtle.right(1)

turtle.hideturtle()
